name: coverage
on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: "1.20.2"
      - uses: actions/checkout@v3
      - run: go test -coverprofile=msak.cov -coverpkg=./... ./...
      - uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: msak.cov
          parallel: true
  finish:
    needs: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: shogo82148/actions-goveralls@v1
        with:
          parallel-finished: true
