name: test
on:
  pull_request:
  push:
    branches:
      - "main"
jobs:
  build_and_run_tests:
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        go: [ "1.19.6" ]
        os: [ "ubuntu-20.04", "windows-2019", "macos-10.15" ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "${{ matrix.go }}"
          cache: true
      - run: go build -v ./...
      - run: go test -race ./...
